name: Build release zip

on:
  push:
    tags: [ 'v*' ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Composer diagnostics
        run: |
          composer --version
          composer config -g repo.packagist composer https://repo.packagist.org
          composer diagnose

      - name: Install dependencies
        run: composer install --no-dev --prefer-dist --optimize-autoloader

      - name: Build plugin zip
        run: |
          PLUGIN=jezweb-compat-audit
          VER=${GITHUB_REF_NAME#v}
          mkdir -p dist
          # Exclude Git and workflow files from the bundle
          zip -r "dist/$PLUGIN-$VER.zip" . \
            -x "*.git*" \
            -x ".github/*" \
            -x "dist/*"

      - name: Attach to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
