name: Build release zip

on:
  push:
    tags: [ 'v*' ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Pull Plugin Update Checker directly (no Composer)
      - name: Vendor plugin-update-checker
        run: |
          mkdir -p vendor
          git clone --depth=1 https://github.com/YahnisElsts/plugin-update-checker.git vendor/plugin-update-checker
          # Clean VCS files to keep the bundle tidy
          rm -rf vendor/plugin-update-checker/.git

      - name: Build plugin zip
        run: |
          set -eux
          PLUGIN=jezweb-compat-audit
          VER="${GITHUB_REF_NAME#v}"
          [ -z "$VER" ] && VER="0.0.0"
          mkdir -p dist
          zip -r "dist/$PLUGIN-$VER.zip" . \
            -x "*.git*" \
            -x ".github/*" \
            -x "dist/*"

      - name: Attach to GitHub Release (if release event)
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifact (for manual runs)
        if: github.event_name != 'release'
        uses: actions/upload-artifact@v4
        with:
          name: plugin-zip
          path: dist/*.zip
